# Generated by Django 5.0.2 on 2024-03-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_genre_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
